### ISSUE TITLE
outdated db/seeds.rb fails with fresh install and setup

### ISSUE THREAD

**Issue by hanmd82** [ruby-bench/ruby-bench-web#124]
When running `bundle exec rake db:setup`, the following error is thrown:

```
  ...  

-- initialize_schema_migrations_table()
   -> 0.0129s
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'unit' for BenchmarkType.

  ... 

/Users/mhan/Desktop/dev/ruby_on_rails/ruby-bench-web/db/seeds.rb:20:in `<top (required)>'
  ... 
```

Here is the specific line in `seeds.rb`:

```
ao_bench = ruby_repo.benchmark_types.create!(
  category: 'ao_bench',
  unit: 'seconds',
  script_url: 'https://raw.githubusercontent.com/ruby/ruby/trunk/benchmark/bm_app_answer.rb'
)
```

Error is thrown due to this migration `20150803163023_remove_unit_from_benchmark_type.rb`.

@tgxworld, should `unit` be removed or replaced with another attribute? What is the design intent?

**Comment by tgxworld** [comment]
Ah this is a little complicated. I'll need to update the seeds file.

If you need it soon, the factory files will give you a good idea

Thanks for reporting!

**Comment by hanmd82** [comment]
Ah it's ok.. I don't need this urgently.. Was just wondering if this would be a simple fix

**Comment by hanmd82** [comment]
while we're at it, another error encountered with `seeds.rb`:

    ActiveRecord::RecordInvalid: Validation failed: Benchmark result type can't be blank
      ...
    /Users/mhan/Desktop/dev/ruby_on_rails/ruby-bench-web/db/seeds.rb:40:in `block in <top (required)>'

This affects all subsequent invocations of `BenchmarkRun.create!` in `seeds.rb`

Tried to patch this up in [PR #125](https://github.com/ruby-bench/ruby-bench-web/pull/125).

Travis CI build failure was at the same point as last known state of the code-base that was already failing, so its not caused by this PR change.
