### ISSUE TITLE
Convert JS to coffeescript

### ISSUE THREAD

**Issue by lalithr95** [ruby-bench/ruby-bench-web#139]
I see all the client side files are in javascript and generally CoffeeScript is preferred because of its syntax and simple for future developers to understand. I liked this idea from GSOC 2016 ideas.

I can make a PR which converts all the JS files to CoffeeScript. 
Let me know your views on it :smiley:

**Comment by tgxworld** [comment]
Hi! I personally dislike the syntax for CoffeeScript. I'm all for converting our JS files to ES6 modules though.

**Comment by lalithr95** [comment]
@tgxworld I will work on that, any input from your side would be great. currently I'm getting familiar with codebase

**Comment by tgxworld** [comment]
Cool let me know if you need any help :)

**Comment by tgxworld** [comment]
Closing this as not an issue
