### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by shlok007** [ruby-bench/ruby-bench-web#175]
Now that rails 5 is out. Upgrading to the new version should be considered.

**Comment by tgxworld** [comment]
Yea we'll want to move to Rails 5 at some point but there isn't anything new in Rails 5 we need right now.

**Comment by shlok007** [comment]
@tgxworld I wish to contribute to ruby-bench-web and was looking for a somewhat easy issue to start with.  :smiley:

**Comment by tgxworld** [comment]
Sure PR welcomed for upgrading us to Rails 5 :) Thank you!!

**Comment by tgxworld** [comment]
This is now done in https://github.com/ruby-bench/ruby-bench-web/commit/1181575bf7e49c456b31f4d35839e29db30beb62
