### ISSUE TITLE
Ruby releases benchmarks end at ruby 2.3.2

### ISSUE THREAD

**Issue by jerryliu55** [ruby-bench/ruby-bench-web#186]
The [release benchmarks](https://rubybench.org/ruby/ruby/releases?result_type=app_lc_fizzbuzz) end at ruby 2.3.2 but other ruby versions have been released after that (2.3.3, 2.4.0).

![image](https://cloud.githubusercontent.com/assets/15824429/22604718/df7bb1d8-ea1a-11e6-886f-3bb3f529500a.png)

@kirs @tgxworld

**Comment by tgxworld** [comment]
Hi Jerry! Hmm I think I didn't run the benchmarks for that release. Will do so once I get to a computer.

**Comment by jerryliu55** [comment]
Thanks! :)

**Comment by tgxworld** [comment]
Closed by https://github.com/ruby-bench/ruby-bench-docker/commit/c60c00164ff1eec1138fc5ba3acf9d0555a35107. The benchmarks are currently running :+1:

**Comment by kirs** [comment]
Thanks Alan!
