### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by bmarkons** [ruby-bench/ruby-bench-web#211]
https://travis-ci.org/ruby-bench/ruby-bench-web/builds/240256064#L602

I can't figure out why this one fails from time to time. It is annoying :sweat:

If anyone has any idea how to fix this, help would be appreciated.

**Comment by tgxworld** [comment]
Maybe just disable the test first. It isn't mission critical in anyway.

**Comment by tgxworld** [comment]
Ok we're skipping it for now :+1:

**Comment by bmarkons** [comment]
https://github.com/ruby-bench/ruby-bench-web/pull/225

**Comment by tgxworld** [comment]
:+1:
