### ISSUE TITLE
Rails suite is broken

### ISSUE THREAD

**Issue by bmarkons** [ruby-bench/ruby-bench-web#239]
https://github.com/rails/rails/commit/089ca520e32e8cd9ebe1075f491d7856683e6cde change broke benchmark suite with following error on `bundle install` : 
```
Bundler could not find compatible versions for gem "arel":
  In Gemfile:
    rails was resolved to 5.2.0.alpha, which depends on
      activerecord (= 5.2.0.alpha) was resolved to 5.2.0.alpha, which depends on
        arel (= 9.0.0.alpha)

```

**Comment by bmarkons** [comment]
Not sure if I am getting this right, but `bundle install` crashes because in ActiveRecord gemspec arel version is 9.0.0.alpha which is not released yet therefore version can't be found?

**Comment by robin850** [comment]
@bmarkons : I didn't test it but I guess you will have to point to the Arel GitHub repository either way now, like:

~~~ruby
gem 'arel', github: 'rails/arel', branch: 'master'

if rails_master?
  gem 'rails', github: 'rails/rails'
  # ...
else
  gem 'rails', path: '/rails'
end
~~~

**Comment by bmarkons** [comment]
Thanks @robin850, that was it! :tada:

**Comment by robin850** [comment]
Awesome ! 🎉
