### ISSUE TITLE
LoadError when requiring pg gem from directory at specific commit

### ISSUE THREAD

**Issue by bmarkons** [ruby-bench/ruby-bench-web#244]
I've made setup for PG suite to be able to run for specific commit, like others.

It works fine when pg gem is required from github though fails when required from directory in which ruby-pg repo is cloned.

I do pull latest changes and `bundle install`, but driver.rb on run can't require `pg` with following error : 
```
/ruby-pg/lib/pg.rb:4:in `require': cannot load such file -- pg_ext (LoadError)
	from /ruby-pg/lib/pg.rb:4:in `<top (required)>'
	from /ruby-bench-suite/pg/benchmarks/pg_suite_runner.rb:6:in `require'
	from /ruby-bench-suite/pg/benchmarks/pg_suite_runner.rb:6:in `<top (required)>'
	from driver.rb:3:in `require_relative'
	from driver.rb:3:in `<main>'
```

https://github.com/ruby-bench/ruby-bench-docker/blob/master/pg/runner

**Comment by tgxworld** [comment]
How is the gem being required from the specific directory?

**Comment by bmarkons** [comment]
I meant this : https://github.com/ruby-bench/ruby-bench-suite/blob/master/pg/Gemfile#L12

When I require it from path it throws error while requiring it from github master works fine (same commit btw).

**Comment by bmarkons** [comment]
I've tried to do it without bundler and do `gem build` and `gem install` and it worked. It could be a possible workaround, though I will investigate a bit more why it's not working in bundler setup.

**Comment by bmarkons** [comment]
Ah, forgot to compile. It's fixed now :ok_hand:

Thanks for having a look at this issue @tgxworld :clap:
