### ISSUE TITLE
Ruby Releases benchmark

### ISSUE THREAD

**Issue by Daniel-ltw** [ruby-bench/ruby-bench-web#262]
Seems like they are not updating on the web. 

Is there some webhook/trigger for that to happen, but have not been run?

**Comment by tgxworld** [comment]
Yup I'll have to trigger it internally :)

**Comment by Daniel-ltw** [comment]
Could you trigger that, so we could have the latest ruby releases versions shown on the site?

**Comment by tgxworld** [comment]
I've already done so but the queue is pretty full at the moment.

**Comment by Daniel-ltw** [comment]
Thanks. Hopefully they will be up tomorrow or the day after.

**Comment by Daniel-ltw** [comment]
Okay. 8 days later, this is still an issue. 

My guess is all benchmarks are sitting on the same queue.
Thus, with others sitting in the queue, although this is queue 8 days ago, it has still not been run. 

Is my guess right? @tgxworld
