### ISSUE TITLE
Logo Creation

### ISSUE THREAD

**Issue by iheartkode** [ruby-bench/ruby-bench-web#44]
I didn't see a logo anywhere so I made one :) 
I have a version that will fit in where your text logo is. 
Also a larger version for others things.
If you need to change the size, make it bigger smaller colors let me know. 

:)

![rubybench_site_version](https://cloud.githubusercontent.com/assets/7018580/6911315/c32664e0-d713-11e4-956a-e68af0a6a1d5.png)
![rubybench](https://cloud.githubusercontent.com/assets/7018580/6911316/c327f31e-d713-11e4-823b-fb38149fbae6.png)

**Comment by tgxworld** [comment]
@iheartkode This is really awesome!! Would you like to throw a PR up to switch our the logo? Do add an attribution to yourself in the footer too :)))

On small note, could we just get the logo without the words? This way we can play around with the font  using CSS. 

cc/ @SamSaffron

**Comment by tgxworld** [comment]
@iheartkode Opps forgot to say thanks!! :+1: :yellow_heart: :purple_heart:

**Comment by iheartkode** [comment]
No problem, I can do that :)

**Comment by SamSaffron** [comment]
awesome!! :heart: :heart:

**Comment by tgxworld** [comment]
@iheartkode Just to be one the safe side, is the gauge used in the image under some form of CC license?

**Comment by iheartkode** [comment]
No, it's open :)

**Comment by iheartkode** [comment]
![rubybench_site_versioncut](https://cloud.githubusercontent.com/assets/7018580/6953003/4a33787a-d87b-11e4-9a14-9a0fc4c7284b.png)

**Comment by iheartkode** [comment]
I always search for free to use images, If I don't find one I draw it.

**Comment by tgxworld** [comment]
> I always search for free to use images, If I don't find one I draw it.

Cool :) Opps sorry one more request. Could we get it with a transparent as well and in a larger size?

Thanks :smile: :smile:

**Comment by iheartkode** [comment]
Np, what size do you prefer? :)

**Comment by tgxworld** [comment]
@iheartkode Did you see my tweet regarding the other logo you created? I think that looks better :smile: 

It'll be great if we could have the following.
- 1650px * 1650px for a transparent background and a colored background without text.
- one with the logo and text. Transparent and colored as well. Though I think we need a bolder font size for the text.

Thanks for all the work! I really like the logo you created :smile:

**Comment by tgxworld** [comment]
![nicer pic](https://cloud.githubusercontent.com/assets/4335742/6991277/ff7be80a-dabc-11e4-94b3-c1732b5b3a40.png)

@SamSaffron I actually prefer this version that @iheartkode made. WDYT?

**Comment by SamSaffron** [comment]
its a bikeshed question :) but honestly not a fan of an upsidown ruby, it kind of sends a bad message out there. I get why it was done, but prefer the original perhaps with the white line de-emphasized a tine bit

**Comment by tgxworld** [comment]
@iheartkode @SamSaffron Cool! Lets stick with the first one then :)

**Comment by iheartkode** [comment]
1650px * 1650px  That's massive.Here it is.
![bitmap](https://cloud.githubusercontent.com/assets/7018580/7007828/dd40923c-dc41-11e4-95f1-84f98edade01.png)

**Comment by iheartkode** [comment]
![bitmap](https://cloud.githubusercontent.com/assets/7018580/7007842/00eea278-dc42-11e4-915e-3a3420df3356.png)
This is massive lol.

**Comment by iheartkode** [comment]
The logo with the words won't fit into 1650 x 1650 without being distorted, since it's not a square.

**Comment by iheartkode** [comment]
![bitmap2](https://cloud.githubusercontent.com/assets/7018580/7007914/c3a2dfbe-dc42-11e4-9456-3bb3a0d6fd2f.png)

**Comment by iheartkode** [comment]
![bitmap3](https://cloud.githubusercontent.com/assets/7018580/7007937/18fba00e-dc43-11e4-81ae-99ebeb861840.png)
Here is a large one with new font

**Comment by iheartkode** [comment]
![bitmap3](https://cloud.githubusercontent.com/assets/7018580/7007969/753c2000-dc43-11e4-9255-175906f97fc5.png)
Larger with words and different font.

**Comment by SamSaffron** [comment]
I find the original font easier to read but love the logo tweak

**Comment by tgxworld** [comment]
> This is massive lol.

@iheartkode Thank you for the images! The image with a transparent background should look something like this :smile: ![](https://github.com/ruby-bench/ruby-bench-web/blob/master/app/assets/images/sponsors/ruby_together.png)

**Comment by iheartkode** [comment]
Opps lol forgot the transparency :P

**Comment by iheartkode** [comment]
Did you want it in .svg or .png

**Comment by iheartkode** [comment]
![33](https://cloud.githubusercontent.com/assets/7018580/7030621/b4255e12-dd1a-11e4-9183-02e3138c840e.png)

This is full transparent

**Comment by iheartkode** [comment]
For some reason github is not showing the transparency

**Comment by iheartkode** [comment]
the one I made show transparent. There is no background.

**Comment by iheartkode** [comment]
Upload it to github then link to me, It should show transparent. it does on my computer and photoshop, My thinking it needs to be uploaded with git.

**Comment by iheartkode** [comment]
Here it is, I forked the repo and pushed the image to assets:
https://github.com/iheartkode/ruby-bench-web/blob/master/app/assets/images/logo_transparent.png

**Comment by iheartkode** [comment]
Just did a pull req :)

**Comment by tgxworld** [comment]
@iheartkode Sorry for nitpicking here but I really want to get this right :smile: 

For the transparent background, This is what I'm seeing on my screen. Not sure if it only applies to me.
![screenshot from 2015-04-08 10 57 10](https://cloud.githubusercontent.com/assets/4335742/7038033/27f37b58-ddde-11e4-8a14-354485173ae9.png)

Also, I'm seeing different colors on the white pointer.
First Upload:
![screenshot from 2015-04-08 10 56 29](https://cloud.githubusercontent.com/assets/4335742/7038044/58fb5dce-ddde-11e4-8cb4-c5ac9ca2b792.png)
After:
![screenshot from 2015-04-08 10 57 00](https://cloud.githubusercontent.com/assets/4335742/7038047/5de6d4d0-ddde-11e4-86b7-6a010714ae99.png)

Last point (sorry!), could we try out a variation using a brighter color of the Ruby logo like the one below?
![screenshot from 2015-04-08 10 56 43](https://cloud.githubusercontent.com/assets/4335742/7038067/87ae39fc-ddde-11e4-99c7-ed9d013e33ab.png)

If you don't mind, you can upload the PSD file too so I can play around with it.

Thank you for all the work!

**Comment by iheartkode** [comment]
Hmm, I will fix that.  Not sure why it changed.

**Comment by iheartkode** [comment]
![rb7](https://cloud.githubusercontent.com/assets/7018580/7039459/26b596f2-dd77-11e4-8df6-822d9c6acd0a.png)
Try this...

**Comment by iheartkode** [comment]
It was not created in Photoshop but Inkscape.

**Comment by iheartkode** [comment]
I can send you the Inkscape file which is an .svg?  And no problem I am happy to help out :)

**Comment by tgxworld** [comment]
![screenshot from 2015-04-08 15 05 08](https://cloud.githubusercontent.com/assets/4335742/7040350/c7b0973a-de00-11e4-9bf7-0e81b55d38d5.png)

Are you seeing the same thing on your screen?

**Comment by iheartkode** [comment]
The outer white line is invisible because the background is white on github and the image is transparent. Maybe when it's uploaded github changes the file. On my computer it's fullyl transparent.

**Comment by iheartkode** [comment]
Maybe I need to email it to you..

**Comment by iheartkode** [comment]
Also what are you trying to do with the image?

**Comment by iheartkode** [comment]
http://imgur.com/SSIYp5p  see here? the white bar shows up because now it has a background. So it's fully transparent.

**Comment by iheartkode** [comment]
https://github.com/iheartkode/ruby-bench-web/blob/master/app/assets/images/rb8.png

**Comment by tgxworld** [comment]
> The outer white line is invisible because the background is white on github and the image is transparent. Maybe when it's uploaded github changes the file. On my computer it's fully transparent.

Cool got it :smile: 

> https://github.com/iheartkode/ruby-bench-web/blob/master/app/assets/images/rb8.png

This is good :)) Thanks!!!

**Comment by tgxworld** [comment]
![rubybench_dark](https://cloud.githubusercontent.com/assets/4335742/7048137/a1cfbe40-de43-11e4-8c41-9ad418fe7510.png)

This is how it'll look with the maroon background.

**Comment by iheartkode** [comment]
Awesome! Let me know if you need anything else. If you want I can do a PR for the  Inkscape SVG file.  Inkscape is an open source vector graphics app.

**Comment by tgxworld** [comment]
Thank you @iheartkode for the logos. We've now updated to a new design. Do let me know if you want stickers and I'll send you some :)
