### ISSUE TITLE
Error pages.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#46]
404, 500 etc..

**Comment by hanmd82** [comment]
@tgxworld what do you have in mind? Style the current templates in the `/public` directory? Add additional info the those pages etc?

**Comment by tgxworld** [comment]
Hey @hanmd82 :smile: 

Yup we just need to update error pages to suite the current style and point nginx at those pages. Actually..I should probably get the nginx config setup even without the error pages XD
