### ISSUE TITLE
Fix tests loading graphs when clicking `back` and `forward`.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#47]
https://github.com/ruby-bench/ruby-bench-web/commit/766374f4ad4e3bd867c6532d304fb1bcde0d4855

Tests are passing on Travis but failed on my local machine.

**Comment by tohyongcheng** [comment]
@tgxworld which tests?

**Comment by tgxworld** [comment]
```
Run options: --seed 5875

# Running:

.......FE.....................

Finished in 30.314135s, 0.9896 runs/s, 5.0142 assertions/s.

  1) Failure:
ViewBenchmarkGraphsTest#test_User_should_see_the_right_message_for_benchmark_types_with_no_benchmark_runs [/home/guoxiang/ruby-bench/ruby-bench-web/test/acceptance/view_benchmark_graphs_test.rb:365]:
Failed assertion, no message given.


  2) Error:
ViewBenchmarkGraphsTest#test_User_should_be_able_to_view_releases_benchmark_graphs_when_they_go_back_and_forward_in_the_broswer_window:
Capybara::ElementNotFound: Unable to find css ".release-chart .highcharts-container .highcharts-yaxis-title"
    test/acceptance/view_benchmark_graphs_test.rb:285:in `block in <class:ViewBenchmarkGraphsTest>'
```

Not sure why...

**Comment by tohyongcheng** [comment]
weird, tests are all passing for me on the latest version. haha, i guess its the capybara webkit stuff again :/ you tried another time?

**Comment by tgxworld** [comment]
This is strange, they pass when I run them individually but I'm getting consistent errors when running `rake test`. I'll find a reliable way to deal with waiting for ajax.

**Comment by tgxworld** [comment]
Note to self: Unrevert [https://github.com/ruby-bench/ruby-bench-web/commit/766374f4ad4e3bd867c6532d304fb1bcde0d4855]
