### ISSUE TITLE
Logster not grabbing any logs in Production

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#53]
Related: https://github.com/ruby-bench/ruby-bench-web/pull/52

![screenshot from 2015-04-17 09 21 22](https://cloud.githubusercontent.com/assets/4335742/7194541/2726de02-e4e3-11e4-9433-3bdd3a3d1460.png)

**Comment by tgxworld** [comment]
cc @SamSaffron Working fine in development. Do you know if it might have something to do with how I'm redirecting the logs in production?

**Comment by SamSaffron** [comment]
are you sure its not working? in prd it only graps warnings and up

**Comment by tgxworld** [comment]
@SamSaffron ![](https://36.media.tumblr.com/tumblr_m8j5w4NTNH1r0hxjuo2_500.jpg)

I totally forgot about that! I'll monitor. Closing this first.

**Comment by tgxworld** [comment]
Thanks :smile:
