### ISSUE TITLE
Bug when selecting benchmark types multiple times.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#63]
![output](https://cloud.githubusercontent.com/assets/4335742/7333611/b99755a2-eba8-11e4-8863-bb1c86c3a039.gif)

**Comment by tohyongcheng** [comment]
@tgxworld as in the previous benchmark type stays there for a while?

**Comment by tgxworld** [comment]
Yea the previous benchmark should be removed immediately.

Date: Sun, 26 Apr 2015 10:17:10 -0700

**Comment by tgxworld** [comment]
Fix in https://github.com/ruby-bench/ruby-bench-web/commit/874470bc9d019a37709e94888ec7472cfa8750b7.
