### ISSUE TITLE
Project switch

### ISSUE THREAD

**Issue by kirs** [ruby-bench/ruby-bench-web#70]
I noticed the redesign PR and I thought that maybe it's time to discuss the projects UI.

Now the web app has basically 2 tabs with benchmarks: releases and per-commit benchmarks. Both of them lead to `ruby/ruby` scope. Since we've got Rails benchmarks (rubybench.org/rails/rails), should we think about the possible way to switch between the projects?

/cc @tgxworld @yangshun

**Comment by tgxworld** [comment]
I guess each of the tabs could link to a mini landing page (Perhaps a table or list) of projects that we have benchmarks for?

**Comment by kirs** [comment]
Sounds good. Can we ask @yangshun do make a mockup of this page?

**Comment by yangshun** [comment]
Sure! I'm tied up this coming week though. I'll resume work on this next next week (:
