### ISSUE TITLE
Add left and right arrow keys to navigate benchmark types

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#78]

**Comment by treble37** [comment]
Hi @tgxworld, did you mean to navigate via the keyboard or just by clicking with the mouse in the browser (this is what my PR does)?

**Comment by tgxworld** [comment]
Hi actually I meant the former :)

**Comment by tgxworld** [comment]
I should have written keyboard shortcuts. Apologies for the confusion

**Comment by treble37** [comment]
No worries, how do you feel about inline javascript for this change?  (I'm personally not the biggest fan, but since this is page specific and pretty small....)

**Comment by tgxworld** [comment]
Sure I'm fine with inline this :)

**Comment by treble37** [comment]
Hrrm...the tests were passing locally with `bundle exec rake test` with both Ruby 2.2.1 and 2.3.1....don't suppose you've ever run into something like this before and have any ideas? :)

**Comment by treble37** [comment]
Ok, tests are green @tgxworld and it's working locally toggling between ao_bench and ab_bench
