### ISSUE TITLE
Fix mobile pages for nexus 7

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#79]
![screenshot from 2015-05-17 22 02 39](https://cloud.githubusercontent.com/assets/4335742/7670672/81cfa248-fce0-11e4-8b89-fe7ca6d02df6.png)

**Comment by yangshun** [comment]
Bootstrap always had a problem with widths wider than 400px and smaller than 768px. I think they'll be adding a new breakpoint soon. Anyways, once we merge the benchmarks, then the navigation won't overflow right?

**Comment by tgxworld** [comment]
Yea I read about that issue as well.

Which benchmarks?

**Comment by yangshun** [comment]
The per-commit and per-release pages can be merged into one single page actually. Use a tab selector to toggle between them.

**Comment by billybonks** [comment]
@yangshun bootstrap emulator says nexus 7 is 900px. ye either merge the links or hack the bootstrap media query to change to burger at 900px or less.

**Comment by tgxworld** [comment]
@billybonks Thanks for the tips! I think we'll probably merge the links soon! :smile:
