### ISSUE TITLE
Height of input box is not the same.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#81]
![screenshot from 2015-05-21 11 52 15](https://cloud.githubusercontent.com/assets/4335742/7741310/e4888dce-ffaf-11e4-8d1b-a57678ca068c.png)

**Comment by yangshun** [comment]
How to reproduce this? Maybe it's just an ubuntu issue. Looks fine on Safari, Chrome and Firefox for Mac :stuck_out_tongue:

**Comment by tgxworld** [comment]
Magically fixed on mine XD closing this with magic.

**Comment by yangshun** [comment]
Must be cuz of #86 :joy:
