### ISSUE TITLE
Raise routing error when no route match instead of throwing errors.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#83]
https://github.com/ruby-bench/ruby-bench-web/blob/master/config/routes.rb#L18-L19

**Comment by tgxworld** [comment]
To be exact this should be throwing 404.

**Comment by hanmd82** [comment]
@tgxworld I'll try this out

**Comment by tgxworld** [comment]
@hanmd82 Cool thanks!!

**Comment by icyflame** [comment]
@tgxworld 

Has this issue been fixed?

I tried to visit [rubybench.com/contributing which is fine](http://rubybench.org/contributing) and [rubybench.com/contribute resulting in 404](http://rubybench.org/contribute).

**Comment by tgxworld** [comment]
Hmm I have to update the issue but what I was referring to are the benchmark routes.

rubybench.org/rails/rails/commits?result_type=activerecord/mysql2_finers_first&display_count

:) If an incorrect result type is passed we should raise not found.

**Comment by tgxworld** [comment]
No longer an issue closing.
