### ISSUE TITLE
RubyBench Logo

### ISSUE THREAD

**Issue by p8952** [ruby-bench/ruby-bench-web#9]
Your Trello page said a logo would be nice.

I'm not graphic designer but I gave it a go. The Ruby logo used in this is licence under CC BY-SA 2.5 so this is as well. Feel free to use it.

![RubyBench_Logo](https://raw.githubusercontent.com/p8952/RubyBench_Logo/master/RubyBench_Logo_Medium.png "RubyBench_Logo")

Different sizes + the SVG can be found [here](https://github.com/p8952/RubyBench_Logo)

**Comment by tgxworld** [comment]
Hey @p8952 thank you for giving a go at the logo. I feel like there is too much going on in the logo though. It's also not clear that the bars represent bar charts. Perhaps we could post the logo at the discussion forum and get more feedback? http://community.rubybench.org/t/we-need-a-logo/11.

Thanks for contributing :heart:

**Comment by tgxworld** [comment]
@p8952  I'm closing this in favor of https://github.com/ruby-bench/ruby-bench-web/issues/44. Thanks for the hard work though!! I really appreciate it.
