### ISSUE TITLE
Ordering broken for releases.

### ISSUE THREAD

**Issue by tgxworld** [ruby-bench/ruby-bench-web#90]
https://github.com/ruby-bench/ruby-bench-web/commit/47b7a094b1974114e5ec30acb8d9c8e321c920d4

![screenshot from 2015-06-16 00 54 43](https://cloud.githubusercontent.com/assets/4335742/8165360/6756f1d4-13c2-11e5-898b-8da4f19b3f4e.png)

**Comment by JuanitoFatas** [comment]
Maybe this could help: https://github.com/github/version_sorter

**Comment by tgxworld** [comment]
@JuanitoFatas Cool! I'll look into it!

**Comment by tgxworld** [comment]
@JuanitoFatas Thanks :kissing_heart:

**Comment by tgxworld** [comment]
Fixed in https://github.com/ruby-bench/ruby-bench-web/commit/401dada50049b38c823e198717f81d99c097c18e

**Comment by JuanitoFatas** [comment]
:+1:
